var Percents = {
    ONESIXTH: 0.1666666666666,
    ONETHIRD: 0.33333333333333,
    HALF: 0.5,
    TWHOTHIRDS: 0.666666666666,
    FIVESIXTHS: 0.83333333333
}, 
Hitmods = {
    ALL: 'all',
    ONES: 'ones',
    MINUSONE: 'minus one',
    PLUSONE: 'plus one'
},
Woundmods = {
    ALL: 'all',
    ONES: 'ones',
    MINUSONE: 'minus one',
    PLUSONE: 'plus one'
},
Damagemods = {
    MINUSONE: 'minus one'
},
PossibleUnits = {
    VANVETCLAW: {
        name: 'Vanguard Veteran w/Lightning Claw',
        models: 10,
        attacks: 3,
        ws: 3,
        strength: 4,
        toughness: 4,
        ap: 2,
        damage: 1,
        hitMod: Hitmods.ALL,
        woundMod: Woundmods.ALL,
        woundMod: Woundmods.PLUSONE,
        save: 2,
        invulnerable: 4,
        wounds: 4
    },
    VANVETPFIST: {
        name: 'Vanguard Veteran w/Power Fist',
        models: 10,
        attacks: 2,
        ws: 3,
        strength: 8,
        toughness: 4,
        ap: 3,
        damage: 2,
        hitMod: Hitmods.MINUSONE,
        hitMod: Hitmods.ALL,
        woundMod: Woundmods.PLUSONE,
        woundMod: '',
        save: 2,
        invulnerable: 4,
        wounds: 2
    },
    VANVETAXE: {
        name: 'Vanguard Veteran w/Axe',
        models: 5,
        attacks: 2,
        ws: 3,
        strength: 6,
        toughness: 4,
        ap: 2,
        damage: 1,
        hitMod: '',
        save: 2,
        invulnerable: 4,
        wounds: 2
    },
    VANVETHEAVYHAMMER: {
        name: 'Vanguard Veteran w/Heavy Hammer',
        models: 1,
        attacks: 3,
        ws: 3,
        strength: 8,
        ap: 3,
        damage: 4,
        hitMod: Hitmods.MINUSONE,
        woundMod: '',
        toughness: 4,
        save: 2,
        invulnerable: 4,
        wounds: 2
    },
    VANVETHAMMER: {
        name: 'Vanguard Veterans w/Thunder Hammers',
        models: 5,
        attacks: 2,
        ws: 3,
        strength: 8,
        ap: 2,
        damage: 3,
        hitMod: Hitmods.MINUSONE,
        toughness: 4,
        save: 2,
        invulnerable: 4,
        wounds: 2
    },
    TERMINATORASSAULT: {
        name: 'Terminator Assault Squad w/Thunder Hammers',
        models: 5,
        attacks: 2,
        ws: 3,
        strength: 8,
        ap: 2,
        damage: 3,
        // hitMod: Hitmods.MINUSONE,
        toughness: 4,
        save: 2,
        invulnerable: 4,
        wounds: 3
    },
    INTERCESSOR: {
        name: 'Intercessors',
        models: 5,
        attacks: 2,
        ws: 3,
        strength: 4,
        ap: 0,
        damage: 1,
        toughness: 4,
        save: 3,
        wounds: 2,
        hitMod: '',
        woundMod: ''
    },
    BLADEGUARD:{
        name: 'Bladeguard Veterans',
        models: 4,
        attacks: 3,
        ws: 3,
        strength: 5,
        ap: 3,
        damage: 2,
        toughness: 4,
        save: 2,
        wounds: 3,
        invulnerable: 4,
    },
    JUDICIAR:{
        name: 'Judiciar',
        models: 1,
        attacks: 4,
        ws: 2,
        strength: 7,
        ap: 3,
        damage: 2,
        toughness: 4,
        save: 3,
        wounds: 5,
        invulnerable: 4,
    },
    IRONCLADDREAD:{
        name: 'Ironclad Dreadnought',
        models: 1,
        attacks: 4,
        ws: 3,
        strength: 12,
        ap: 4,
        damage: 6,
        toughness: 8,
        save: 3,
        wounds: 8,
        hitMod: Hitmods.ONES,
        damageMod: Damagemods.MINUSONE
    },
    CENTURIONASSAULT:{
        name: 'Centurion Assault Squad',
        models: 3,
        attacks: 3,
        ws: 3,
        strength: 10,
        ap: 4,
        damage: 3,
        toughness: 5,
        save: 2,
        wounds: 4
    },
    COMPANYCHAMPION:{
        name: 'Company Champion w/burning blade & imperiums sword',
        models: 1,
        attacks: 6,
        ws: 2,
        strength: 8,
        ap: 5,
        damage: 2,
        toughness: 4,
        save: 2,
        invulnerable: 5,
        wounds: 4,
    },
    REDEMPTORHEAVYGATTLING:{
        name: 'Redemptor Dreadnought heavy gatling cannon',
        models: 1,
        attacks: 12,
        ws: 3,
        strength: 6,
        ap: 1,
        damage: 1,
        toughness: 7,
        save: 3,
        wounds: 13,
        damageMod: Damagemods.MINUSONE
    },
    REDEMPTORONSLAUGHT:{
        name: 'Redemptor Dreadnought onslaught gatling cannon',
        models: 1,
        attacks: 8,
        ws: 3,
        strength: 5,
        ap: 1,
        damage: 1,
        toughness: 7,
        save: 3,
        wounds: 13
    },
    CONTEMPTORSHOOTING:{
        name: 'Contemptor Dreadnought shooting',
        models: 1,
        attacks: 16,
        ws: 2,
        strength: 6,
        ap: 0,
        damage: 2,
        toughness: 7,
        save: 3,
        wounds: 9,
        // hitMod: Hitmods.ONES,
    },
    HELLBLASTERSHOOTING:{
        name: 'Hellblasters shooting',
        models: 5,
        attacks: 3,
        ws: 3,
        strength: 6,
        ap: 4,
        damage: 1,
        toughness: 4,
        save: 3,
        wounds: 2,
        // woundMod: Woundmods.MINUSONE
    },
    GRAVCANNONDEVS:{
        name: 'Devastators with Grav Cannons',
        models: 5,
        attacks: 4,
        ws: 3,
        strength: 5,
        ap: 3,
        damage: 2,
        toughness: 4,
        save: 3,
        wounds: 2,
        woundMod: Woundmods.MINUSONE
    },
    MULTIMELTA:{
        name: '1 Multi Melta',
        models: 1,
        attacks: 2,
        ws: 3,
        strength: 8,
        ap: 4,
        damage: 3,
        toughness: 4,
        save: 3,
        wounds: 2,
    },
    PLAGUEMARINE: {
        name: 'Plague Marine',
        toughness: 5,
        save: 3,
        wounds: 2,
        invulnerable: 0,
        damageMod: Damagemods.MINUSONE,
        strength: 4,
        attacks: 2,
        ap: 1,
        damage: 1
    },
    CARNIFEX: {
        name: 'Carnifex',
        toughness: 7,
        save: 3,
        wounds: 8,
        invulnerable: 0,
        strength: 6,
        attacks: 4,
        ap: 3,
        damage: 3
    },
    POXWALKER: {
        name: "Poxwalker",
        toughness: 4,
        strength: 3,
        ws: 4,
        wounds: 1,
        attacks: 2,
        damageMod: Damagemods.MINUSONE,
        save: 7,
        ap: 0,
        damage: 1
    },
    HORAMGAUNTS: {
        name: 'Hormagaunts',
        toughness: 3,
        save: 6,
        wounds: 1,
        invulnerable: 0,
        strength: 3,
        attacks: 2,
        ap: 0,
        damage: 1
    },
    TYRANIDWARRIORS:{
        name: 'Tyranid Warriors',
        models: 10,
        attacks: 4,
        ws: 3,
        strength: 4,
        toughness: 4,
        ap: 0,
        damage: 1,
        save: 4,
        wounds: 3
    },
    HIVEGUARD:{
        name: 'Hiveguard',
        models: 6,
        attacks: 2,
        ws: 3,
        strength: 8,
        toughness: 5,
        ap: 2,
        damage: 2,
        save: 4,
        wounds: 3
    },
    ZOANTHROPE:{
        name: 'Zoanthropes',
        models: 3,
        attacks: 1,
        ws: 4,
        strength: 4,
        toughness: 5,
        ap: 0,
        damage: 1,
        save: 5,
        invulnerable: 3,
        wounds: 3
    },
    PBC: {
        name: 'Plagueburst Crawler',
        models: 1,
        toughness: 8,
        save: 3,
        wounds: 12,
        ws: 3,
        invulnerable: 5,
        damageMod: Damagemods.MINUSONE,
        strength: 8,
        attacks: 3,
        ap: 2,
        damage: 2
    },
    FOETICDRONE:{
        name: 'Foetid Bloat Drone',
        models: 1,
        attacks: 12,
        ws: 3,
        strength: 7,
        toughness: 7,
        ap: 2,
        damage: 2,
        damageMod: Damagemods.MINUSONE,
        save: 3,
        invulnerable: 5,
        wounds: 9
    },
    DEATHSHROUD: {
        name: 'Deathshroud Terminators',
        models: 5,
        toughness: 5,
        save: 2,
        wounds: 3,
        invulnerable: 4,
        damageMod: Damagemods.MINUSONE,
        strength: 7,
        attacks: 4,
        ap: 3,
        damage: 2
    },
    BLIGHTHAULER:{
        name: 'Mythic Blight hauler',
        models: 1,
        attacks: 4,
        ws: 3,
        strength: 6,
        toughness: 7,
        ap: 2,
        damage: 1,
        save: 3,
        invulnerable: 5,
        woundMod: Woundmods.ONES,
        damageMod: Damagemods.MINUSONE,
        wounds: 9
    },
    HIVETYRANT: {
        name: 'Hive Tyrant',
        toughness: 7,
        strength: 6,
        save: 3,
        wounds: 12,
        invulnerable: 4,
        attacks: 5,
        ap: 3,
        damage: 3
    },
    KNIGHTMAGAERA: {
        name: "Knight Magaera",
        toughness: 8,
        strength: 8,
        ws: 3,
        wounds: 24,
        attacks: 12,
        save: 3,
        invulnerable: 5,
        ap: 2,
        damage: 3
    },
    IRONSTRIDER:{
        name: "Ironstrider Balistirii",
        toughness: 6,
        strength: 9,
        ws: 3,
        wounds: 6,
        attacks: 2,
        save: 3,
        invulnerable: 6,
        ap: 3,
        damage: 4
    },
    BOYZ:{
        name: "Ork Boyz",
        toughness: 5,
        strength: 4,
        ws: 3,
        wounds: 1,
        attacks: 3,
        save: 6,
        ap: 0,
        damage: 1
    },
    WARBOSSONBIKE: {
        name: "Ork Warboss on Warbike",
        toughness: 7,
        strength: 7,
        ws: 2,
        wounds: 7,
        attacks: 5,
        save: 4,
        invulnerable: 4,
        ap: 2,
        damage: 3
    },
    RAIDER: {
        name: "Drukhari Raider",
        models: 1,
        toughness: 6,
        strength: 6,
        ws: 4,
        wounds: 10,
        attacks: 1,
        save: 4,
        invulnerable: 5,
        ap: 1,
        damage: 1
    },
    WYCHES:{
        name: "Drukhari Wyches",
        models: 5,
        toughness: 4,
        strength: 4,
        ws: 3,
        wounds: 1,
        attacks: 4,
        save: 6,
        invulnerable: 4,
        ap: 1,
        damage: 1
    },
    INCUBI:{
        name: "Drukhari Incubi",
        models: 5,
        toughness: 3,
        strength: 5,
        ws: 2,
        wounds: 1,
        attacks: 3,
        save: 3,
        invulnerable: 5,
        ap: 3,
        damage: 1
    }
}